[package]
name = "chopsticks-executor"
description = "Chopsticks executor"
repository = "https://github.com/AcalaNetwork/chopsticks"
license = ""
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
getrandom = { version = "0.2", default-features = false, features = ["js"] }
serde = { version = "1.0.136", default-features = false }
serde_json = { version = "1.0", default-features = false }
hex = { version = "0.4.3", default-features = false }
hex-literal = "0.3.4"
wasm-bindgen = "0.2.83"
serde-wasm-bindgen = "0.4.5"
wasm-bindgen-futures = "0.4.33"
js-sys = "0.3.60"
log = { version = "0.4.17", features = ["std"] }
console_error_panic_hook = "0.1.7"
console_log = "0.2.0"

smoldot = { path = '../vendor/smoldot', default-features = false }

[dev-dependencies]
arrayvec = { version = "0.7.2", default-features = false }

[features]
default = []
std = [
    "smoldot/std"
]
