endpoint:
  - wss://kusama.api.encointer.org
mock-signature-host: true
block: ${env.ENCOINTER_KUSAMA_BLOCK_NUMBER}
db: ./encointer-kusama.db.sqlite
runtime-log-level: 5
# wasm-override: integritee_runtime.wasm

import-storage:
  System:
    Account:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - providers: 1
          data:
            free: 1000000000000000
  Council:
    Members:
      - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
