
endpoint:
  - wss://phala-rpc.dwellir.com
  - wss://phala.api.onfinality.io/public-ws
mock-signature-host: true
block: ${env.PHALA_BLOCK_NUMBER}
db: ./phala.db.sqlite
# wasm-override: thala_parachain_runtime.compact.compressed.wasm

import-storage:
  Sudo:
    Key: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY # Alice
  System:
    Account:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - providers: 1
          data:
            free: 1000000000000000
  TechnicalCommittee:
    Members: ["5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"]
  Council:
    Members: ["5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"]
