endpoint: wss://rpc.composablenodes.tech
mock-signature-host: true
block: 1935395
db: ./picasso.kusama.db.sqlite
# wasm-override: ../../ComposableFi/composable/result/lib/runtime.optimized.wasm

import-storage:
  Sudo:
    Key: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY # Alice
  System:
    Account:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - data:
            free: 1000000000000000
