endpoint: wss://subsocial-rpc.dwellir.com/
mock-signature-host: true
block: ${env.SUBSOCIAL_BLOCK_NUMBER}
db: ./subsocial.db.sqlite
runtime-log-level: 5

import-storage:
  System:
    Account:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - providers: 1
          data:
            free: 1000000000000000

