name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          executor/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly-2022-10-16
        components: rustfmt
        target: wasm32-unknown-unknown
        default: true
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'yarn'
    - run: yarn build-wasm
    - run: yarn --immutable
    - run: yarn check
    - run: yarn lint
    - run: yarn test
  publish:
    - name: Publish chopsticks
      uses: JS-DevTools/npm-publish@v1
      if: github.event_name == "push"
      with:
        token: ${{ secrets.NPM_AUTH_TOKEN }}
        package: ../../package.json
        dry-run: true
    - name: Publish chopsticks-executor
      uses: JS-DevTools/npm-publish@v1
      if: github.event_name == "push"
      with:
        token: ${{ secrets.NPM_AUTH_TOKEN }}
        package: ../../executor/pkg/package.json
        dry-run: true

