name: Publish

on:
  push:
    branches: [ master, pkg-build ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          executor/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly-2022-10-16
        components: rustfmt
        target: wasm32-unknown-unknown
        default: true
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'yarn'
        registry-url: https://registry.npmjs.org/
    - run: yarn --immutable
    - run: yarn check
    - run: yarn build-wasm
    - run: yarn build
    - name: Publish @acala-network/chopsticks
      run: yarn npm publish --tolerate-republish --access public
      env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - name: Publish @acala-network/chopsticks-executor
      run: yarn workspace @acala-network/chopsticks-executor npm publish --tolerate-republish --access public
      env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      